name: Build artifact

# Controls when the action will run.
on:
  release:
    types: [published]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup cross compiler
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-linux-gnueabihf
          echo "CC=arm-linux-gnueabihf-gcc" >> $GITHUB_ENV

      - name: run the buildscript
        run: /bin/sh build-static-tmux.sh

      - name: Upload artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: "/tmp/tmux-static/bin/tmux.*.gz"
          replacesArtifacts: true
          allowUpdates: true
          bodyFile: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
